####################################################################
# VSTS Build Configuration, Version 1.4
#
# (c)2021 superdev GmbH
####################################################################

name: $[format('{0}', variables['buildName'])]

pool:
  vmImage: 'windows-2019'

trigger:
  branches:
    include:
    - master
    - develop
    - feature/*
    - bugfix/*

  paths:
    exclude:
    - README.md
    - Images/*
    - Samples/*

variables:
  solution: 'NuGetUtils.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  majorVersion: 2
  minorVersion: 2
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    # Versioning: 1.0.0
    patchVersion: $[counter(format('{0}.{1}.{2}', variables.majorVersion, variables.minorVersion), 0)]
    semVersion: $[format('{0}.{1}.{2}', variables.majorVersion, variables.minorVersion, variables.patchVersion)]
  ${{ if and(ne(variables['Build.SourceBranch'], 'refs/heads/master'), eq(startsWith(variables['Build.SourceBranch'], 'refs/pull/'), 'false') }}:
    # Versioning: 1.0.0-pre.123
    semVersionBase: $[format('{0}.{1}.{2}-pre', variables.majorVersion, variables.minorVersion, 0)]
    semVersionRev: $[counter(variables.semVersionBase, 0)]
    semVersion: $[format('{0}.{1}', variables.semVersionBase, variables.semVersionRev)]
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}: # Pull requests
    # Versioning: 1.0.0-pr.1.123
    semVersionBase: $[format('{0}.{1}.{2}-pr.{3}', variables.majorVersion, variables.minorVersion, 0, variables['System.PullRequest.PullRequestId'])]
    semVersionRev: $[counter(variables.semVersionBase, 0)]
    semVersion: $[format('{0}.{1}', variables.semVersionBase, variables.semVersionRev)]
  buildName: $[format('{0}', variables.semVersion)]

steps:
- task: Bash@3
  displayName: 'Print all variables'
  inputs:
    targetType: 'inline'
    script: 'env | sort'
   
- task: Assembly-Info-NetCore@2
  displayName: 'Update Assembly Info'
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: |
      **/*.csproj
    InsertAttributes: true
    FileEncoding: 'auto'
    WriteBOM: false
    Product: 'NuGetUtils'
    Description: ''
    Company: 'superdev GmbH'
    Copyright: '(c) $(date:YYYY) superdev GmbH'
    VersionNumber: '$(Build.BuildNumber)'
    FileVersionNumber: '$(Build.BuildNumber)'
    InformationalVersion: '$(Build.BuildNumber)'
    PackageVersion: '$(Build.BuildNumber)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: false'


- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 5.x'
  inputs:
    versionSpec: 5.x

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(solution)'
    msbuildArgs: ''
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    
- task: DotNetCoreCLI@2
  displayName: 'Run UnitTests'
  inputs:
    command: test
    projects: '**/*.Tests.csproj'
    arguments: '--no-restore --no-build --configuration $(buildConfiguration)'
    
- task: DotNetCoreCLI@2
  displayName: 'Pack NuGetUtils'
  inputs:
    command: pack
    packagesToPack: NuGetUtils/NuGetUtils.csproj
    versioningScheme: byEnvVar
    versionEnvVar: semVersion

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGetUtils.CLI'
  inputs:
    command: pack
    packagesToPack: NuGetUtils.CLI/NuGetUtils.CLI.csproj
    versioningScheme: byEnvVar
    versionEnvVar: semVersion

- task: CmdLine@2
  displayName: 'Publish NuGetUtils.CLI'
  inputs:
    script: |
      dotnet publish NuGetUtils.CLI/NuGetUtils.CLI.csproj --configuration $(BuildConfiguration) --runtime win10-x64 --self-contained=false /p:PublishSingleFile=true --output=$(Build.ArtifactStagingDirectory)\NuGetUtils.CLI\publish --no-dependencies

- task: ArchiveFiles@2
  displayName: 'Zip Archive NuGetUtils.CLI'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)\NuGetUtils.CLI\publish'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/NuGetUtils.CLI/publish/NuGetUtils.CLI_$(semVersion).zip'
    replaceExistingArchive: true

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'

    Contents: |
     **\bin\$(BuildConfiguration)\**
     **\bin\*.nupkg

    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
